version: '2'
services:
    smartjournal-postgresql:
        image: postgres:10.4
        # volumes:
        #     - ~/volumes/jhipster/smartjournal/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=smartjournal
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
